changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@devtools-ds/object-inspector@*":
    peerDependencies:
      react-dom: "*"
  "@devtools-ds/themes@*":
    peerDependencies:
      react-dom: "*"
  "@devtools-ds/tree@*":
    peerDependencies:
      react-dom: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/telemetry@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/testing-library@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
