compressionLevel: 0

defaultSemverRangePrefix: ^

enableGlobalCache: true

nmSelfReferences: false

nodeLinker: node-modules

packageExtensions:

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
