changesetIgnorePatterns:
  - "**/dist/*"
  - "**/packages/*"
  - "**/.*"
  - .**/*

compressionLevel: mixed

enableGlobalCache: false

nmHoistingLimits: none

nodeLinker: node-modules

packageExtensions:
  "@storybook/mdx1-csf@*":
    peerDependencies:
      react: "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
